<div class="dashboard-hero mb-4"><div class="d-flex justify-content-between align-items-center"><div><h2 class="mb-1">Pengaturan Aplikasi</h2><div class="subtitle">Identitas toko, logo, dan database</div></div><div></div></div></div>
<div class="row g-4"><div class="col-lg-6"><div class="card"><div class="card-body"><h5 class="card-title">Informasi Toko</h5>
<form id="set-form" enctype="multipart/form-data"><div class="mb-2"><label class="form-label">Nama Toko</label><input type="text" name="store_name" id="store_name" class="form-control" required></div><div class="mb-2"><label class="form-label">No. Telepon</label><input type="tel" name="store_phone" id="store_phone" pattern="[0-9]+" class="form-control"></div><div class="mb-2"><label class="form-label">Alamat</label><textarea name="store_address" id="store_address" class="form-control" rows="2"></textarea></div><div class="mb-2"><label class="form-label">Footer Invoice</label><textarea name="store_footer" id="store_footer" class="form-control" rows="2" placeholder="Terima kasih atas kepercayaan Anda"></textarea></div><div class="mb-2"><label class="form-label">Logo</label><input type="file" name="logo" id="logo" class="form-control" accept="image/*"></div><div class="d-grid gap-2 mt-2"><button type="submit" class="btn btn-primary"><i class="bi bi-save me-2"></i>Simpan</button><button type="button" class="btn btn-outline-primary" id="set-reset"><i class="bi bi-plus-square me-2"></i>Bersihkan</button></div></form>
</div></div></div>
<div class="col-lg-6"><div class="card"><div class="card-body"><h5 class="card-title">Database</h5>
<form id="db-form"><div class="row g-2"><div class="col-md-6"><label class="form-label">Host</label><input type="text" id="db_host" class="form-control" placeholder="localhost"></div><div class="col-md-6"><label class="form-label">Port</label><input type="text" id="db_port" class="form-control" placeholder="3306"></div><div class="col-md-6"><label class="form-label">Nama DB</label><input type="text" id="db_name" class="form-control" placeholder="jasaku_pos"></div><div class="col-md-6"><label class="form-label">User</label><input type="text" id="db_user" class="form-control" placeholder="root"></div><div class="col-md-12"><label class="form-label">Password</label><input type="password" id="db_pass" class="form-control" placeholder="(kosong untuk XAMPP)"></div></div><div class="d-grid gap-2 mt-2"><button type="submit" class="btn btn-primary"><i class="bi bi-save me-2"></i>Simpan</button><button type="button" class="btn btn-outline-primary" id="db-reset"><i class="bi bi-plus-square me-2"></i>Bersihkan</button></div></form>
</div></div></div>
<div class="col-lg-6"><div class="card"><div class="card-body"><h5 class="card-title">Preview</h5>
<div class="text-center"><img id="logo-preview" src="" alt="Logo" style="max-width:260px; max-height:120px; object-fit:contain"></div>
<div class="mt-3 small text-muted" id="set-hint">Perubahan akan diterapkan pada invoice POS dan halaman yang menampilkan identitas toko.</div>
</div></div></div></div>
<script>
const SAPI='../api/settings.php';function loadSettings(){fetch(SAPI).then(r=>r.json()).then(d=>{if(!d.ok)return;const x=d.data||{};document.getElementById('store_name').value=x.store_name||'';document.getElementById('store_phone').value=x.store_phone||'';document.getElementById('store_address').value=x.store_address||'';document.getElementById('store_footer').value=x.store_footer||'';const lp=document.getElementById('logo-preview');let path=(x.store_logo||'');if(path.startsWith('public/')){path=path.slice(7);}const root=window.location.pathname.replace(/index\.php.*/,'');const url=path? (path.startsWith('/')?path:(root+path)) : '';lp.src=url? (url+"?v="+Date.now()) : '';
document.getElementById('db_host').value=x.db_host||'';document.getElementById('db_port').value=x.db_port||'';document.getElementById('db_name').value=x.db_name||'';document.getElementById('db_user').value=x.db_user||'';document.getElementById('db_pass').value='';
});}
document.getElementById('logo').addEventListener('change',function(){const f=this.files&&this.files[0];if(!f)return;const r=new FileReader();r.onload=function(e){document.getElementById('logo-preview').src=e.target.result;};r.readAsDataURL(f);});
document.getElementById('set-form').addEventListener('submit',function(e){e.preventDefault();const fd=new FormData(this);fetch(SAPI,{method:'POST',body:fd}).then(r=>r.json()).then(d=>{if(d.ok){loadSettings();}});});
document.getElementById('set-reset').addEventListener('click',function(){document.getElementById('set-form').reset();document.getElementById('logo-preview').src='';});
document.getElementById('db-form').addEventListener('submit',function(e){e.preventDefault();const body=new URLSearchParams();body.set('mode','db');body.set('db_host',document.getElementById('db_host').value.trim());body.set('db_port',document.getElementById('db_port').value.trim());body.set('db_name',document.getElementById('db_name').value.trim());body.set('db_user',document.getElementById('db_user').value.trim());body.set('db_pass',document.getElementById('db_pass').value);fetch(SAPI,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:body.toString()}).then(r=>r.json()).then(d=>{if(d.ok){loadSettings();}});});
document.getElementById('db-reset').addEventListener('click',function(){document.getElementById('db-form').reset();});
loadSettings();
</script>
