<div class="dashboard-hero mb-4"><div class="d-flex justify-content-between align-items-center"><div><h2 class="mb-1">POS</h2><div class="subtitle">Transaksi penjualan dan pembayaran</div></div><div></div></div></div>
<div class="row g-4"><div class="col-lg-6"><div class="card"><div class="card-body"><h5 class="card-title">Transaksi Baru</h5>
<form id="sale-form"><div class="row g-2"><div class="col-md-6"><label class="form-label">Pelanggan</label><input type="text" id="sale-cust" class="form-control" list="cust-dl" placeholder="Ketik nama lalu pilih"><datalist id="cust-dl"></datalist><div id="sale-cust-hint" class="form-text"></div></div><div class="col-md-6"><label class="form-label">Metode Bayar</label><select id="sale-pay" class="form-select"><option value="Tunai">Tunai</option><option value="Transfer">Transfer</option><option value="QRIS">QRIS</option></select></div></div>
<div class="mt-2"><label class="form-label">Item</label><div class="row g-2"><div class="col-6"><input type="text" id="si-name" class="form-control" list="item-dl" placeholder="Nama item"><datalist id="item-dl"><?php if (isset($items) && is_array($items)) { foreach ($items as $it) { $nm = trim($it['name'] ?? ''); echo '<option value="'.htmlspecialchars($nm).'">'; } } ?></datalist><div id="si-hint" class="form-text"></div></div><div class="col-3"><input type="number" id="si-qty" class="form-control" placeholder="Qty" value="1"></div><div class="col-3"><input type="number" step="0.01" id="si-price" class="form-control" placeholder="Harga"></div></div><div id="si-msg" class="mt-2"></div><div class="d-grid mt-2"><button class="btn btn-outline-secondary" type="button" id="si-add"><i class="bi bi-plus"></i> Tambah</button></div></div>
<div class="table-responsive mt-2"><table class="table table-sm"><thead><tr><th>Item</th><th class="text-end">Qty</th><th class="text-end">Harga</th><th class="text-end">Subtotal</th><th></th></tr></thead><tbody id="si-list"></tbody><tfoot><tr><td colspan="3" class="text-end">Total</td><td class="text-end" id="sale-total">Rp0</td><td></td></tr></tfoot></table></div>
<div id="sale-msg" class="mt-2"></div><div class="d-grid gap-2 mt-2"><button type="submit" class="btn btn-primary"><i class="bi bi-cash-coin me-2"></i>Simpan Transaksi</button><button type="button" class="btn btn-outline-primary" id="sale-reset"><i class="bi bi-plus-square me-2"></i>Bersihkan</button></div></form>
</div></div></div>
<div class="col-lg-6"><div class="card"><div class="card-body">
<div class="d-flex justify-content-between align-items-center mb-2"><h5 class="card-title mb-0">Transaksi Terakhir</h5><div class="input-group" style="max-width:280px;"><span class="input-group-text"><i class="bi bi-search"></i></span><input type="text" id="sale-search" class="form-control" placeholder="Cari kode/pelanggan"></div></div>
<div class="table-responsive"><table class="table table-hover"><thead><tr><th>Kode</th><th>Pelanggan</th><th>Bayar</th><th>Total</th><th>Tanggal</th><th>Aksi</th></tr></thead><tbody id="sale-list"></tbody></table></div>
</div></div></div></div>
<script>
const ORI=window.location.origin;const API_BASE=(window.APP_API_BASE||'/');function mkApi(p){try{return new URL(p, ORI+API_BASE).href;}catch(e){return API_BASE+p;}}const SAPI=mkApi('api/sales.php');const IAPI=mkApi('api/items.php');const CAPI=mkApi('api/customers.php');function fmtIDR(n){return 'Rp '+(Number(n||0)).toLocaleString('id-ID');}
let ITEMMAP={};let SITEMS=[];let CUSTMAP={};
try{const INIT_ITEMS=<?= json_encode(isset($items)&&is_array($items)?$items:[]) ?>;if(Array.isArray(INIT_ITEMS)){INIT_ITEMS.forEach(function(x){const nm=(String(x.name||''))?.trim?.()||String(x.name||'');const key=nm.toLowerCase();if(!ITEMMAP[key]){ITEMMAP[key]={id:parseInt(x.id||0,10),name:nm,price:Number(x.price||0),stock:parseInt(x.stock||0,10)};}});} }catch(e){}
function loadItems(){fetch(IAPI).then(r=>r.json()).then(d=>{if(!d.ok)return;ITEMMAP={};const dl=document.getElementById('item-dl');dl.innerHTML='';(d.data||[]).forEach(x=>{const nm=(x.name||'').trim();const key=nm.toLowerCase();ITEMMAP[key]=x;const o=document.createElement('option');o.value=nm;dl.appendChild(o);});syncItemFields();}).catch(()=>{});}
function loadCustomers(){fetch(CAPI).then(r=>r.json()).then(d=>{if(!d.ok)return;CUSTMAP={};const dl=document.getElementById('cust-dl');dl.innerHTML='';(d.data||[]).forEach(x=>{const name=(x.name||'');CUSTMAP[name.toLowerCase()]=x;const o=document.createElement('option');o.value=name;dl.appendChild(o);});});}
function getCustomerByName(name){return CUSTMAP[(name||'').toLowerCase()]||null;}
function syncCustomerHint(){const name=document.getElementById('sale-cust').value.trim();const c=getCustomerByName(name);const hint=document.getElementById('sale-cust-hint');if(!hint)return;if(c){const phone=c.phone?(' | HP: '+c.phone):'';const email=c.email?(' | Email: '+c.email):'';hint.textContent=(c.name||'')+phone+email;}else{hint.textContent='';}}
function getItemByName(name){const key=(name||'').trim().toLowerCase();if(ITEMMAP[key]) return ITEMMAP[key];let best=null;for(const k in ITEMMAP){if(k===key){return ITEMMAP[k];}if(k.includes(key) || key.includes(k)){best=ITEMMAP[k];}}return best;}
function getReservedQty(name){const key=(name||'').trim().toLowerCase();let sum=0;SITEMS.forEach(it=>{if(((it.name||'').trim().toLowerCase())===key){sum+=Number(it.qty||0);}});return sum;}
function setMsg(html,cls){const el=document.getElementById('si-msg');if(!el)return;el.className='';if(cls)el.classList.add('alert',cls);el.innerHTML=html||'';}
function ensureItemLoaded(name){const q=(name||'').trim();if(!q)return Promise.resolve();return fetch(IAPI+'?q='+encodeURIComponent(q)).then(r=>r.json()).then(d=>{if(!d.ok)return;const dl=document.getElementById('item-dl');(d.data||[]).forEach(x=>{const nm=(x.name||'').trim();const key=nm.toLowerCase();if(!ITEMMAP[key]){ITEMMAP[key]=x;const o=document.createElement('option');o.value=nm;dl.appendChild(o);}});}).catch(()=>{});}
function syncItemFields(){const name=document.getElementById('si-name').value.trim();const item=getItemByName(name);const hint=document.getElementById('si-hint');const addBtn=document.getElementById('si-add');if(item){const p=document.getElementById('si-price');if(p){p.value=Number(item.price||0);} const reserved=getReservedQty(name);const remain=Math.max(0, Number(item.stock||0)-reserved); if(hint){hint.textContent='Stok: '+String(item.stock||0)+' | Sisa: '+String(remain)+' | Harga: '+fmtIDR(item.price||0);} if(addBtn){addBtn.disabled=false;}} else {ensureItemLoaded(name).then(function(){const it2=getItemByName(name);if(it2){const p=document.getElementById('si-price');if(p){p.value=Number(it2.price||0);} const reserved=getReservedQty(name);const remain=Math.max(0, Number(it2.stock||0)-reserved); if(hint){hint.textContent='Stok: '+String(it2.stock||0)+' | Sisa: '+String(remain)+' | Harga: '+fmtIDR(it2.price||0);} if(addBtn){addBtn.disabled=false;}} else {if(hint){hint.textContent='Item tidak ditemukan di inventori';} if(addBtn){addBtn.disabled=true;}}});}
  validateQty();}
function validateQty(){const name=document.getElementById('si-name').value.trim();const item=getItemByName(name);const qEl=document.getElementById('si-qty');const val=Number(qEl.value||0);if(!item){setMsg('Pilih item dari inventori', 'alert-warning');return;}const stk=Number(item.stock||0);const reserved=getReservedQty(name);const allowed=Math.max(0, stk-reserved);if(stk<=0){setMsg('Stok item kosong', 'alert-warning');} else {setMsg('',null);}if(val>allowed){qEl.value=allowed;setMsg('Qty melebihi sisa stok ('+allowed+'), disesuaikan ke '+allowed, 'alert-warning');}}
function renderSItems(){const tbody=document.getElementById('si-list');let total=0;tbody.innerHTML=SITEMS.map((it,i)=>{const sub=(Number(it.qty)||0)*(Number(it.price)||0);total+=sub;return `<tr><td>${it.name||''}</td><td class='text-end'>${it.qty||0}</td><td class='text-end'>${fmtIDR(it.price||0)}</td><td class='text-end'>${fmtIDR(sub)}</td><td class='text-end'><button type='button' class='btn btn-sm btn-outline-danger' onclick='delSi(${i})'><i class=\"bi bi-x\"></i></button></td></tr>`}).join('');document.getElementById('sale-total').innerText=fmtIDR(total);}function delSi(i){SITEMS.splice(i,1);renderSItems();}
document.getElementById('si-name').addEventListener('input',function(){syncItemFields();});
document.getElementById('si-name').addEventListener('blur',function(){syncItemFields();});
document.getElementById('si-name').addEventListener('change',function(){syncItemFields();});
document.getElementById('si-qty').addEventListener('input',function(){validateQty();});
document.getElementById('sale-cust').addEventListener('input',function(){syncCustomerHint();});
document.getElementById('si-add').addEventListener('click',function(){const name=document.getElementById('si-name').value.trim();const qty=Number(document.getElementById('si-qty').value||0);if(!name||qty<=0)return;const item=getItemByName(name);if(!item){setMsg('Item tidak ditemukan di inventori', 'alert-warning');return;}const item_id=item.id;const reserved=getReservedQty(name);const stk=Number(item.stock||0);const allowed=Math.max(0, stk-reserved);if(qty>allowed){setMsg('Qty melebihi sisa stok ('+allowed+')', 'alert-warning');return;}const nm=(item.name||'').trim();const price=Number(item.price||0);SITEMS.push({item_id,name:nm,qty,price});document.getElementById('si-name').value='';document.getElementById('si-qty').value='1';document.getElementById('si-price').value='';document.getElementById('si-hint').textContent='';setMsg('',null);renderSItems();});
function loadSales(){fetch(SAPI).then(r=>r.json()).then(d=>{if(!d.ok)return;const q=document.getElementById('sale-search').value.toLowerCase();const rows=(d.data||[]).filter(x=>(x.code||'').toLowerCase().includes(q)||(x.customer_name||'').toLowerCase().includes(q));const tbody=document.getElementById('sale-list');tbody.innerHTML=rows.map(x=>`<tr><td>${x.code||''}</td><td>${x.customer_name||''}</td><td>${x.payment_method||''}</td><td>${fmtIDR(x.total||0)}</td><td>${x.created_at||''}</td><td><div class='btn-group btn-group-sm'><button class='btn btn-outline-primary' onclick='viewSale("${x.token}")'><i class='bi bi-eye'></i></button><button class='btn btn-outline-secondary' onclick='printInv("${x.token}","a4")'><i class="bi bi-file-earmark-text"></i> A4</button><button class='btn btn-outline-secondary' onclick='printInv("${x.token}","thermal",80)'><i class="bi bi-file-earmark"></i> Thermal 80</button><button class='btn btn-outline-secondary' onclick='printInv("${x.token}","thermal",58)'><i class="bi bi-file-earmark"></i> Thermal 58</button></div></td></tr>`).join('');});}
let PF=null;function printInv(t,type,w){if(!PF){PF=document.createElement('iframe');PF.style.position='fixed';PF.style.width='0';PF.style.height='0';PF.style.border='0';PF.style.bottom='0';PF.style.right='0';document.body.appendChild(PF);}const url=`index.php?r=pos/invoice&t=${encodeURIComponent(t)}&type=${encodeURIComponent(type)}${type==='thermal'&&w?`&w=${encodeURIComponent(w)}`:''}`;PF.onload=function(){try{PF.contentWindow.focus();PF.contentWindow.print();}catch(e){}};PF.src=url;}
function viewSale(t){fetch(SAPI+'?t='+encodeURIComponent(t)).then(r=>r.json()).then(d=>{if(!d.ok||!d.data)return;const s=d.data;const lines=(s.items||[]).map(it=>`${it.item_name||''} x ${it.qty} = ${fmtIDR((Number(it.qty)||0)*(Number(it.price)||0))}`).join('\n');alert(`Kode: ${s.code}\nPelanggan: ${s.customer_name||''}\nMetode: ${s.payment_method||''}\nTotal: ${fmtIDR(s.total||0)}\n\nItem:\n${lines}`);});}
function setSaleMsg(html,cls){const el=document.getElementById('sale-msg');if(!el)return;el.className='';if(cls)el.classList.add('alert',cls);el.innerHTML=html||'';}
document.getElementById('sale-form').addEventListener('submit',function(e){e.preventDefault();const btn=e.submitter||document.querySelector('#sale-form button[type="submit"]');if(btn){btn.disabled=true;}const cust=document.getElementById('sale-cust').value.trim();const c=getCustomerByName(cust);const payload={customer_name:c?c.name:cust,payment_method:document.getElementById('sale-pay').value,items:SITEMS.map(it=>({item_id:it.item_id,qty:it.qty,price:it.price}))};fetch(SAPI,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(async r=>{if(!r.ok)throw new Error('HTTP '+r.status);let d;try{d=await r.json();}catch(_){d={ok:true};}return d;}).then(d=>{if(d.ok){setSaleMsg('',null);document.getElementById('sale-form').reset();SITEMS=[];renderSItems();loadSales();}else{setSaleMsg(d.error||'Gagal menyimpan transaksi','alert-danger');}}).catch(err=>{setSaleMsg((err&&err.message)||'Gagal menyimpan transaksi','alert-danger');}).finally(()=>{if(btn){btn.disabled=false;}});});
document.getElementById('sale-reset').addEventListener('click',function(){document.getElementById('sale-form').reset();SITEMS=[];renderSItems();syncCustomerHint();syncItemFields();});document.getElementById('sale-search').addEventListener('input',loadSales);loadItems();loadCustomers();renderSItems();syncItemFields();loadSales();
</script>
