<div class="dashboard-hero mb-4"><div class="d-flex justify-content-between align-items-center"><div><h2 class="mb-1">Inventori</h2><div class="subtitle">Kelola item dan stok</div></div><div></div></div></div>
<div class="row g-4"><div class="col-lg-5"><div class="card"><div class="card-body"><h5 class="card-title">Form Item</h5>
<form id="item-form"><input type="hidden" id="item-id"><div class="mb-2"><label class="form-label">Nama</label><input type="text" id="item-name" class="form-control" required></div><div class="mb-2"><label class="form-label">SKU</label><input type="text" id="item-sku" class="form-control"></div><div class="mb-2"><label class="form-label">Harga</label><div class="input-group"><span class="input-group-text">Rp</span><input type="number" step="0.01" id="item-price" class="form-control"></div></div><div class="mb-2"><label class="form-label">Stok</label><input type="number" id="item-stock" class="form-control" value="0"></div><div class="mb-2"><label class="form-label">Min Stok</label><input type="number" id="item-min" class="form-control" value="0"></div><div class="d-grid gap-2 mt-2"><button type="submit" class="btn btn-primary"><i class="bi bi-save me-2"></i>Simpan</button><button type="button" class="btn btn-outline-primary" id="item-reset"><i class="bi bi-plus-square me-2"></i>Bersihkan</button></div></form>
</div></div></div>
<div class="col-lg-7"><div class="card"><div class="card-body">
<div class="d-flex justify-content-between align-items-center mb-2"><h5 class="card-title mb-0">Daftar Item</h5><div class="input-group" style="max-width:280px;"><span class="input-group-text"><i class="bi bi-search"></i></span><input type="text" id="item-search" class="form-control" placeholder="Cari nama/SKU"></div></div>
<div class="table-responsive"><table class="table table-hover"><thead><tr><th>Nama</th><th>SKU</th><th>Harga</th><th>Stok</th><th>Min</th><th>Aksi</th></tr></thead><tbody id="item-list"></tbody></table></div>
</div></div></div></div>
<script>const ROLE='<?= htmlspecialchars($_SESSION['role'] ?? '') ?>'; const IAPI='../api/items.php';function loadItems(){fetch(IAPI).then(r=>r.json()).then(d=>{if(!d.ok)return;const q=document.getElementById('item-search').value.toLowerCase();const rows=(d.data||[]).filter(x=>(x.name||'').toLowerCase().includes(q)||(x.sku||'').toLowerCase().includes(q));const tbody=document.getElementById('item-list');tbody.innerHTML=rows.map(x=>{const adjBtn = ROLE==='admin'?`<button class='btn btn-outline-secondary' onclick='adjItem("${x.token}")'><i class='bi bi-arrow-repeat'></i></button>`:'';return `<tr><td>${x.name||''}</td><td>${x.sku||''}</td><td>Rp ${(Number(x.price||0)).toLocaleString('id-ID')}</td><td>${x.stock||0}</td><td>${x.min_stock||0}</td><td><div class='btn-group btn-group-sm'><button class='btn btn-outline-primary' onclick='editItem("${x.token}")'><i class='bi bi-pencil'></i></button>${adjBtn}<button class='btn btn-outline-danger' onclick='delItem("${x.token}")'><i class='bi bi-trash'></i></button></div></td></tr>`;}).join('');});}
function editItem(t){fetch(IAPI+'?t='+encodeURIComponent(t)).then(r=>r.json()).then(d=>{if(!d.ok||!d.data)return;const x=d.data;document.getElementById('item-id').value=x.id;document.getElementById('item-name').value=x.name||'';document.getElementById('item-sku').value=x.sku||'';document.getElementById('item-price').value=x.price||'';document.getElementById('item-stock').value=x.stock||0;document.getElementById('item-min').value=x.min_stock||0;});}
function delItem(t){if(!confirm('Hapus item ini?'))return;fetch(IAPI+'?t='+encodeURIComponent(t),{method:'DELETE'}).then(r=>r.json()).then(d=>{if(d.ok)loadItems();});}
document.getElementById('item-form').addEventListener('submit',function(e){e.preventDefault();const id=document.getElementById('item-id').value;const payload={id:id?parseInt(id,10):undefined,name:document.getElementById('item-name').value.trim(),sku:document.getElementById('item-sku').value.trim(),price:document.getElementById('item-price').value,stock:parseInt(document.getElementById('item-stock').value||'0',10),min_stock:parseInt(document.getElementById('item-min').value||'0',10)};const method=id?'PUT':'POST';fetch(IAPI,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(r=>r.json()).then(d=>{if(d.ok){document.getElementById('item-form').reset();document.getElementById('item-id').value='';loadItems();}});});
function adjItem(t){const deltaStr=prompt('Masukkan perubahan stok (contoh: +5 atau -3)','');if(deltaStr===null)return;const delta=parseInt(deltaStr,10);if(isNaN(delta)||delta===0){alert('Nilai tidak valid');return;}const note=prompt('Catatan penyesuaian','Penyesuaian Stok')||'Penyesuaian Stok';fetch(IAPI,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({t,action:'adjust',delta:delta,note:note})}).then(r=>r.json()).then(d=>{if(d.ok){loadItems();}else{alert(d.error||'Gagal penyesuaian');}});}
document.getElementById('item-reset').addEventListener('click',function(){document.getElementById('item-form').reset();document.getElementById('item-id').value='';});document.getElementById('item-search').addEventListener('input',loadItems);loadItems();</script>
