<div class="dashboard-hero mb-4"><div class="d-flex justify-content-between align-items-center"><div><h2 class="mb-1">Kelola Tiket</h2><div class="subtitle">Tambah, ubah, hapus tiket perbaikan</div></div><div></div></div></div>
<div class="row g-4"><div class="col-lg-5"><div class="card"><div class="card-body"><h5 class="card-title">Form Tiket</h5>
<form id="tkt-form"><input type="hidden" id="tkt-id"><input type="hidden" id="tkt-cust-token">
<div class="mb-2"><label class="form-label">Kode</label><input type="text" id="tkt-code" class="form-control" placeholder="Kosongkan untuk otomatis"></div>
<div class="mb-2"><label class="form-label">Nama Pelanggan</label><input type="text" id="tkt-cust" class="form-control" list="cust-dl" placeholder="Ketik nama lalu pilih" required><datalist id="cust-dl"></datalist></div>
<div class="mb-2"><label class="form-label">No HP</label><input type="text" id="tkt-phone" class="form-control" required></div>
<div class="mb-2"><label class="form-label">Perangkat</label><input type="text" id="tkt-device" class="form-control" required></div>
<div class="mb-2"><label class="form-label">Merk</label><input type="text" id="tkt-brand" class="form-control"></div>
<div class="mb-2"><label class="form-label">Model</label><input type="text" id="tkt-model" class="form-control"></div>
<div class="mb-2"><label class="form-label">Serial Number</label><input type="text" id="tkt-serial" class="form-control"></div>
<div class="mb-2"><label class="form-label">Aksesori Dibawa</label><input type="text" id="tkt-acc" class="form-control" placeholder="Charger, kabel, dll"></div>
<div class="mb-2"><label class="form-label">Status</label><select id="tkt-status" class="form-select"><option>Baru</option><option>Dalam Pemeriksaan</option><option>Dalam Perbaikan</option><option>Menunggu Sparepart</option><option>Selesai</option><option>Dibatalkan</option></select></div>
<div class="mb-2"><label class="form-label">Estimasi Harga</label><div class="input-group"><span class="input-group-text">Rp</span><input type="number" step="0.01" id="tkt-price" class="form-control" placeholder="0"></div></div>
<div class="mb-2"><label class="form-label">Cara Pembayaran</label><select id="tkt-pay" class="form-select"><option value="Tunai">Tunai</option><option value="Transfer">Transfer</option><option value="QRIS">QRIS</option></select></div>
<div class="mb-2"><label class="form-label">Deskripsi</label><textarea id="tkt-desc" class="form-control" rows="2"></textarea></div>
<div class="mb-3">
  <label class="form-label">Komponen Biaya</label>
  <div class="row g-2">
    <div class="col-6"><input type="text" id="ci-name" class="form-control" placeholder="Nama biaya"></div>
    <div class="col-3"><input type="number" id="ci-qty" class="form-control" placeholder="Qty" value="1"></div>
    <div class="col-3"><input type="number" step="0.01" id="ci-price" class="form-control" placeholder="Harga"></div>
  </div>
  <div class="d-grid mt-2"><button type="button" class="btn btn-outline-secondary" id="ci-add"><i class="bi bi-plus"></i> Tambah Komponen</button></div>
  <div class="table-responsive mt-2"><table class="table table-sm"><thead><tr><th>Nama</th><th class="text-end">Qty</th><th class="text-end">Harga</th><th class="text-end">Subtotal</th><th></th></tr></thead><tbody id="ci-list"></tbody><tfoot><tr><td colspan="3" class="text-end">Total</td><td class="text-end" id="ci-total">Rp0</td><td></td></tr></tfoot></table></div>
</div>
<div class="d-grid gap-2 mt-2"><button type="submit" class="btn btn-primary"><i class="bi bi-save me-2"></i>Simpan</button><button type="button" class="btn btn-outline-primary" id="tkt-reset"><i class="bi bi-plus-square me-2"></i>Bersihkan</button></div></form>
</div></div></div>
<div class="col-lg-7"><div class="card"><div class="card-body">
<div class="d-flex justify-content-between align-items-center mb-2"><h5 class="card-title mb-0">Daftar Tiket</h5><div class="input-group" style="max-width:280px;"><span class="input-group-text"><i class="bi bi-search"></i></span><input type="text" id="tkt-search" class="form-control" placeholder="Cari kode/nama"></div></div>
<div class="table-responsive"><table class="table table-hover"><thead><tr><th>Kode</th><th>Pelanggan</th><th>Perangkat</th><th>Status</th><th>Update</th><th>Aksi</th></tr></thead><tbody id="tkt-list"></tbody></table></div>
</div></div></div></div>
<script>const TAPI='../api/tickets.php';const CAPI='../api/customers.php';
let ITEMS=[];function renderItems(){const tbody=document.getElementById('ci-list');let total=0;tbody.innerHTML=ITEMS.map((it,i)=>{const sub=(Number(it.qty)||0)*(Number(it.price)||0);total+=sub;return `<tr><td>${it.name||''}</td><td class='text-end'>${it.qty||0}</td><td class='text-end'>Rp ${Number(it.price||0).toLocaleString('id-ID')}</td><td class='text-end'>Rp ${sub.toLocaleString('id-ID')}</td><td class='text-end'><button type='button' class='btn btn-sm btn-outline-danger' onclick='delItem(${i})'><i class="bi bi-x"></i></button></td></tr>`}).join('');document.getElementById('ci-total').innerText='Rp '+total.toLocaleString('id-ID');document.getElementById('tkt-price').value=String(total);}function delItem(i){ITEMS.splice(i,1);renderItems();}
document.getElementById('ci-add').addEventListener('click',function(){const name=document.getElementById('ci-name').value.trim();const qty=Number(document.getElementById('ci-qty').value||0);const price=Number(document.getElementById('ci-price').value||0);if(!name||qty<=0||price<=0)return;ITEMS.push({name,qty,price});document.getElementById('ci-name').value='';document.getElementById('ci-qty').value='1';document.getElementById('ci-price').value='';renderItems();});
function loadTickets(){fetch(TAPI).then(r=>r.json()).then(d=>{if(!d.ok)return;const q=document.getElementById('tkt-search').value.toLowerCase();const rows=(d.data||[]).filter(x=>(x.code||'').toLowerCase().includes(q)||(x.customer_name||'').toLowerCase().includes(q));const tbody=document.getElementById('tkt-list');tbody.innerHTML=rows.map(x=>`<tr><td>${x.code||''}</td><td>${x.customer_name||''}</td><td>${x.device_type||''}</td><td><span class='badge badge-status'>${x.status||''}</span></td><td>${x.updated_at||''}</td><td><div class='btn-group btn-group-sm'><button class='btn btn-outline-primary' onclick='editT("${x.token}")'><i class='bi bi-pencil'></i></button><button class='btn btn-outline-danger' onclick='delT("${x.token}")'><i class='bi bi-trash'></i></button><button class='btn btn-outline-secondary' onclick='printInv("${x.token}","a4")'><i class="bi bi-file-earmark-text"></i> Invoice A4</button><button class='btn btn-outline-secondary' onclick='printInv("${x.token}","thermal")'><i class="bi bi-file-earmark"></i> Invoice Thermal</button><button class='btn btn-outline-secondary' onclick='printSlip("${x.token}","thermal")'><i class="bi bi-ticket"></i> Ticket Thermal</button></div></td></tr>`).join('');});}
function printSlip(t,type){if(!PF){PF=document.createElement('iframe');PF.style.position='fixed';PF.style.width='0';PF.style.height='0';PF.style.border='0';PF.style.bottom='0';PF.style.right='0';document.body.appendChild(PF);}const url=`index.php?r=ticket/slip&t=${encodeURIComponent(t)}&type=${encodeURIComponent(type)}`;PF.onload=function(){try{PF.contentWindow.focus();PF.contentWindow.print();}catch(e){}};PF.src=url;}
let PF=null;function printInv(t,type,w){if(!PF){PF=document.createElement('iframe');PF.style.position='fixed';PF.style.width='0';PF.style.height='0';PF.style.border='0';PF.style.bottom='0';PF.style.right='0';document.body.appendChild(PF);}const url=`index.php?r=ticket/invoice&t=${encodeURIComponent(t)}&type=${encodeURIComponent(type)}${w?`&w=${w}`:''}`;PF.onload=function(){try{PF.contentWindow.focus();PF.contentWindow.print();}catch(e){}};PF.src=url;}
let CUSTMAP={};function loadCustomers(){fetch(CAPI).then(r=>r.json()).then(d=>{if(!d.ok)return;CUSTMAP={};const dl=document.getElementById('cust-dl');dl.innerHTML='';(d.data||[]).forEach(x=>{const label=(x.name||'')+' ('+(x.phone||'')+')';CUSTMAP[label]=x;const opt=document.createElement('option');opt.value=label;opt.dataset.token=x.token;dl.appendChild(opt);});});}
document.getElementById('tkt-cust').addEventListener('change',function(){const v=this.value;const m=CUSTMAP[v];if(m){document.getElementById('tkt-phone').value=m.phone||'';document.getElementById('tkt-cust-token').value=m.token||'';}});
function editT(t){fetch(TAPI+'?t='+encodeURIComponent(t)).then(r=>r.json()).then(d=>{if(!d.ok||!d.data)return;const x=d.data;document.getElementById('tkt-id').value=x.id;document.getElementById('tkt-code').value=x.code||'';document.getElementById('tkt-cust').value=x.customer_name||'';document.getElementById('tkt-phone').value=x.phone||'';document.getElementById('tkt-device').value=x.device_type||'';document.getElementById('tkt-brand').value=x.brand||'';document.getElementById('tkt-model').value=x.model||'';document.getElementById('tkt-serial').value=x.serial_number||'';document.getElementById('tkt-acc').value=x.accessories||'';document.getElementById('tkt-status').value=x.status||'Baru';document.getElementById('tkt-price').value=x.estimate_price||'';document.getElementById('tkt-pay').value=x.payment_method||'Tunai';document.getElementById('tkt-desc').value=x.description||'';ITEMS=[];try{const arr=x.cost_items?JSON.parse(x.cost_items):[];if(Array.isArray(arr))ITEMS=arr;}catch(e){}renderItems();});}
function delT(t){if(!confirm('Hapus tiket ini?'))return;fetch(TAPI+'?t='+encodeURIComponent(t),{method:'DELETE'}).then(r=>r.json()).then(d=>{if(d.ok)loadTickets();});}
document.getElementById('tkt-form').addEventListener('submit',function(e){e.preventDefault();const id=document.getElementById('tkt-id').value;const cname=document.getElementById('tkt-cust').value.trim();const mapped=CUSTMAP[cname];const payload={id:id?parseInt(id,10):undefined,code:document.getElementById('tkt-code').value.trim(),customer_name:mapped?mapped.name:cname,phone:mapped?mapped.phone:document.getElementById('tkt-phone').value.trim(),device_type:document.getElementById('tkt-device').value.trim(),brand:document.getElementById('tkt-brand').value.trim(),model:document.getElementById('tkt-model').value.trim(),serial_number:document.getElementById('tkt-serial').value.trim(),accessories:document.getElementById('tkt-acc').value.trim(),estimate_price:document.getElementById('tkt-price').value.trim(),payment_method:document.getElementById('tkt-pay').value.trim(),status:document.getElementById('tkt-status').value.trim(),description:document.getElementById('tkt-desc').value.trim(),cost_items:ITEMS};const method=id?'PUT':'POST';fetch(TAPI,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(r=>r.json()).then(d=>{if(d.ok){document.getElementById('tkt-form').reset();document.getElementById('tkt-id').value='';document.getElementById('tkt-cust-token').value='';ITEMS=[];renderItems();loadTickets();}});});
document.getElementById('tkt-reset').addEventListener('click',function(){document.getElementById('tkt-form').reset();document.getElementById('tkt-id').value='';document.getElementById('tkt-cust-token').value='';});document.getElementById('tkt-search').addEventListener('input',loadTickets);loadTickets();loadCustomers();</script>
