<div class="dashboard-hero mb-4"><div class="d-flex justify-content-between align-items-center"><div><h2 class="mb-1">Pricelist</h2><div class="subtitle">Kelola daftar harga layanan</div></div><div></div></div></div>
<div class="row g-4"><div class="col-lg-5"><div class="card"><div class="card-body"><h5 class="card-title">Form Layanan</h5>
<form id="pl-form"><input type="hidden" id="pl-id"><div class="mb-2"><label class="form-label">Nama Layanan</label><input type="text" id="pl-name" class="form-control" required></div><div class="mb-2"><label class="form-label">Kategori</label><input type="text" id="pl-cat" class="form-control" placeholder="Contoh: Laptop, HP"></div><div class="mb-2"><label class="form-label">Harga</label><div class="input-group"><span class="input-group-text">Rp</span><input type="number" step="0.01" id="pl-price" class="form-control"></div></div><div class="mb-2"><label class="form-label">Deskripsi</label><textarea id="pl-desc" class="form-control" rows="2" placeholder="Catatan layanan, ketentuan, dll"></textarea></div><div class="form-check mb-2"><input class="form-check-input" type="checkbox" id="pl-active" checked><label class="form-check-label" for="pl-active">Aktif</label></div><div class="d-grid gap-2 mt-2"><button type="submit" class="btn btn-primary"><i class="bi bi-save me-2"></i>Simpan</button><button type="button" class="btn btn-outline-primary" id="pl-reset"><i class="bi bi-plus-square me-2"></i>Bersihkan</button></div></form>
</div></div></div>
<div class="col-lg-7"><div class="card"><div class="card-body">
<div class="d-flex justify-content-between align-items-center mb-2"><h5 class="card-title mb-0">Daftar Layanan</h5><div class="input-group" style="max-width:280px;"><span class="input-group-text"><i class="bi bi-search"></i></span><input type="text" id="pl-search" class="form-control" placeholder="Cari nama/kategori"></div></div>
<div class="table-responsive"><table class="table table-hover"><thead><tr><th>Nama</th><th>Kategori</th><th class="text-end">Harga</th><th>Status</th><th>Aksi</th></tr></thead><tbody id="pl-list"></tbody></table></div>
</div></div></div></div>
<script>
const PAPI='../api/pricelist.php';function fmtIDR(n){return 'Rp '+(Number(n||0)).toLocaleString('id-ID');}
function loadPL(){fetch(PAPI).then(r=>r.json()).then(d=>{if(!d.ok)return;const q=document.getElementById('pl-search').value.toLowerCase();const rows=(d.data||[]).filter(x=>(x.name||'').toLowerCase().includes(q)||(x.category||'').toLowerCase().includes(q));const tbody=document.getElementById('pl-list');tbody.innerHTML=rows.map(x=>`<tr><td>${x.name||''}</td><td>${x.category||''}</td><td class='text-end'>${fmtIDR(x.price||0)}</td><td>${(x.active?'<span class="badge bg-success">Aktif</span>':'<span class="badge bg-secondary">Nonaktif</span>')}</td><td><div class='btn-group btn-group-sm'><button class='btn btn-outline-primary' onclick='editPL("${x.token}")'><i class='bi bi-pencil'></i></button><button class='btn btn-outline-danger' onclick='delPL("${x.token}")'><i class='bi bi-trash'></i></button></div></td></tr>`).join('');});}
function editPL(t){fetch(PAPI+'?t='+encodeURIComponent(t)).then(r=>r.json()).then(d=>{if(!d.ok||!d.data)return;const x=d.data;document.getElementById('pl-id').value=x.id;document.getElementById('pl-name').value=x.name||'';document.getElementById('pl-cat').value=x.category||'';document.getElementById('pl-price').value=x.price||'';document.getElementById('pl-desc').value=x.description||'';document.getElementById('pl-active').checked=!!x.active;});}
function delPL(t){if(!confirm('Hapus layanan ini?'))return;fetch(PAPI+'?t='+encodeURIComponent(t),{method:'DELETE'}).then(r=>r.json()).then(d=>{if(d.ok)loadPL();});}
document.getElementById('pl-form').addEventListener('submit',function(e){e.preventDefault();const id=document.getElementById('pl-id').value;const payload={id:id?parseInt(id,10):undefined,name:document.getElementById('pl-name').value.trim(),category:document.getElementById('pl-cat').value.trim(),price:document.getElementById('pl-price').value,description:document.getElementById('pl-desc').value.trim(),active:document.getElementById('pl-active').checked?1:0};const method=id?'PUT':'POST';fetch(PAPI,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(r=>r.json()).then(d=>{if(d.ok){document.getElementById('pl-form').reset();document.getElementById('pl-id').value='';document.getElementById('pl-active').checked=true;loadPL();}});});
document.getElementById('pl-reset').addEventListener('click',function(){document.getElementById('pl-form').reset();document.getElementById('pl-id').value='';document.getElementById('pl-active').checked=true;});document.getElementById('pl-search').addEventListener('input',loadPL);loadPL();
</script>
