<div class="dashboard-hero mb-4"><div class="d-flex justify-content-between align-items-center"><div><h2 class="mb-1">Laporan</h2><div class="subtitle">Ringkasan dan detail tiket</div></div><div><div class="btn-group"><a href="index.php?r=report/index" class="btn btn-success">Laporan Tiket</a><a href="index.php?r=report/purchase" class="btn btn-outline-warning">Laporan Pembelian</a><a href="index.php?r=report/sales" class="btn" style="border:1px solid #fd7e14;color:#fd7e14">Laporan Penjualan</a></div></div></div></div>
<form class="card mb-3"><div class="card-body"><div class="row g-2 align-items-end"><div class="col-sm-3"><label class="form-label">Dari</label><input type="date" id="r-from" class="form-control" value="<?= htmlspecialchars($from) ?>"></div><div class="col-sm-3"><label class="form-label">Sampai</label><input type="date" id="r-to" class="form-control" value="<?= htmlspecialchars($to) ?>"></div><div class="col-sm-3"><label class="form-label">Status</label><select id="r-status" class="form-select"><option value="" <?= $status===''?'selected':'' ?>>Semua</option><option <?= $status==='Baru'?'selected':'' ?>>Baru</option><option <?= $status==='Dalam Pemeriksaan'?'selected':'' ?>>Dalam Pemeriksaan</option><option <?= $status==='Dalam Perbaikan'?'selected':'' ?>>Dalam Perbaikan</option><option <?= $status==='Menunggu Sparepart'?'selected':'' ?>>Menunggu Sparepart</option><option <?= $status==='Selesai'?'selected':'' ?>>Selesai</option><option <?= $status==='Dibatalkan'?'selected':'' ?>>Dibatalkan</option></select></div><div class="col-sm-3 d-grid"><button type="button" id="r-apply" class="btn btn-primary"><i class="bi bi-funnel me-2"></i>Terapkan</button></div></div></div></form>
<div class="row g-3 mb-3">
<div class="col-md-3"><div class="card card-stat"><div class="card-body"><div class="d-flex align-items-center"><i class="bi bi-ticket-detailed text-primary fs-3 me-3"></i><div><div class="stat-value"><?= (int)($summary['total'] ?? 0) ?></div><div class="stat-label">Total Tiket</div></div></div></div></div></div>
<div class="row g-3 mb-3">
<div class="col-md-2"><div class="card"><div class="card-body"><div class="small">Baru</div><div class="h5 mb-0"><?= (int)($summary['baru'] ?? 0) ?></div></div></div></div>
<div class="col-md-2"><div class="card"><div class="card-body"><div class="small">Dalam Pemeriksaan</div><div class="h5 mb-0"><?= (int)($summary['periksa'] ?? 0) ?></div></div></div></div>
<div class="col-md-2"><div class="card"><div class="card-body"><div class="small">Dalam Perbaikan</div><div class="h5 mb-0"><?= (int)($summary['perbaikan'] ?? 0) ?></div></div></div></div>
<div class="col-md-2"><div class="card"><div class="card-body"><div class="small">Menunggu Sparepart</div><div class="h5 mb-0"><?= (int)($summary['sparepart'] ?? 0) ?></div></div></div></div>
<div class="col-md-2"><div class="card"><div class="card-body"><div class="small">Selesai</div><div class="h5 mb-0"><?= (int)($summary['selesai'] ?? 0) ?></div></div></div></div>
<div class="col-md-2"><div class="card"><div class="card-body"><div class="small">Dibatalkan</div><div class="h5 mb-0"><?= (int)($summary['batal'] ?? 0) ?></div></div></div></div>
</div>
<div class="row g-3 mb-3">
<div class="col-md-3"><div class="card"><div class="card-body"><div class="small">Total Estimasi</div><div class="h5 mb-0">Rp <?= number_format((float)($summary['total_est'] ?? 0),0,',','.') ?></div></div></div></div>
</div>
<div class="card"><div class="card-body">
<div class="d-flex justify-content-between align-items-center mb-2"><h5 class="card-title mb-0">Detail Tiket</h5></div>
<div class="table-responsive" style="max-height: 460px; overflow-y: auto;"><table class="table table-hover"><thead><tr><th>Kode</th><th>Pelanggan</th><th>Perangkat</th><th>Status</th><th>Estimasi</th><th>Update</th></tr></thead><tbody id="tkt-body">
<?php foreach ($rows as $x): ?>
<tr><td><?= htmlspecialchars($x['code'] ?? '') ?></td><td><?= htmlspecialchars($x['customer_name'] ?? '') ?></td><td><?= htmlspecialchars($x['device_type'] ?? '') ?></td><td><span class="badge badge-status"><?= htmlspecialchars($x['status'] ?? '') ?></span></td><td>Rp <?= number_format((float)($x['estimate_price'] ?? 0),0,',','.') ?></td><td><?= htmlspecialchars($x['updated_at'] ?? '') ?></td></tr>
<?php endforeach; if (empty($rows)): ?>
<tr><td colspan="6" class="text-muted">Belum ada data</td></tr>
<?php endif; ?>
</tbody></table></div>
</div></div>
<script>document.getElementById('r-apply').addEventListener('click',function(){const f=document.getElementById('r-from').value;const t=document.getElementById('r-to').value;const s=document.getElementById('r-status').value;const usp=new URLSearchParams(window.location.search);usp.set('from',f);usp.set('to',t);usp.set('status',s);window.location.search=usp.toString();});(function(){const tb=document.getElementById('tkt-body');if(!tb)return;const rows=Array.from(tb.querySelectorAll('tr'));const hasDataRow=rows.some(function(tr){const tds=tr.querySelectorAll('td');return tds.length>=6 && String(tds[0].textContent||'').trim()!=='';});const isEmptyMsg=rows.length===1 && rows[0].querySelector('td') && String(rows[0].querySelector('td').textContent||'').includes('Belum ada data');if(hasDataRow||isEmptyMsg){return;}const paths=['../api/tickets.php','api/tickets.php'];function tryLoad(i){if(i>=paths.length)return;fetch(paths[i],{credentials:'same-origin'}).then(r=>r.json()).then(d=>{if(!d||!d.ok){tryLoad(i+1);return;}const rws=Array.isArray(d.data)?d.data:[];tb.innerHTML='';rws.forEach(function(x){const tr=document.createElement('tr');tr.innerHTML=`<td>${String(x.code||'')}</td><td>${String(x.customer_name||'')}</td><td>${String(x.device_type||'')}</td><td><span class='badge badge-status'>${String(x.status||'')}</span></td><td>Rp ${(Number(x.estimate_price||0)).toLocaleString('id-ID')}</td><td>${String(x.updated_at||'')}</td>`;tb.appendChild(tr);});}).catch(function(){tryLoad(i+1);});}tryLoad(0);} )();</script>
