<div class="dashboard-hero mb-4"><div class="d-flex justify-content-between align-items-center"><div><h2 class="mb-1">Laporan Penjualan POS</h2><div class="subtitle">Ringkasan transaksi dan item terlaris</div></div><div><div class="btn-group"><a href="index.php?r=report/index" class="btn btn-outline-success">Laporan Tiket</a><a href="index.php?r=report/purchase" class="btn btn-outline-warning">Laporan Pembelian</a><a href="index.php?r=report/sales" class="btn" style="background-color:#fd7e14;border-color:#fd7e14;color:#fff">Laporan Penjualan</a></div></div></div></div>
<div class="card mb-3"><div class="card-body"><form method="get" action="index.php"><input type="hidden" name="r" value="report/sales"><div class="row g-2 align-items-end"><div class="col-sm-3"><label class="form-label">Dari</label><input type="date" name="from" class="form-control" value="<?= htmlspecialchars($from) ?>"></div><div class="col-sm-3"><label class="form-label">Sampai</label><input type="date" name="to" class="form-control" value="<?= htmlspecialchars($to) ?>"></div><div class="col-sm-3"><label class="form-label">Metode Bayar</label><input type="text" name="payment_method" class="form-control" value="<?= htmlspecialchars($pay) ?>" placeholder="mis: Cash / Transfer / QRIS"></div><div class="col-sm-3"><label class="form-label">Kode Transaksi</label><input type="text" name="code" class="form-control" value="<?= htmlspecialchars($code) ?>" placeholder="mis: SL-62E8BF"></div><div class="col-sm-3"><button class="btn btn-primary w-100" type="submit"><i class="bi bi-filter"></i> Terapkan</button></div></div></form></div></div>
<div class="row g-3">
  <div class="col-lg-4">
    <div class="card"><div class="card-body"><div class="d-flex justify-content-between"><div>Total Transaksi</div><div class="fw-bold"><?= (int)($summary['tx_count'] ?? 0) ?></div></div><hr><div class="d-flex justify-content-between"><div>Total Nilai</div><div class="fw-bold">Rp <?= number_format((float)($summary['total_amount'] ?? 0),0,',','.') ?></div></div></div></div>
    <div class="card mt-3"><div class="card-body"><h5 class="mb-3">Breakdown Metode Bayar</h5><?php $totAmt=(float)($summary['total_amount']??0); foreach (($payBreak??[]) as $pb): $amt=(float)($pb['amount']??0); $pct=$totAmt>0?round(($amt/$totAmt)*100):0; ?><div class="mb-2"><div class="d-flex justify-content-between"><div><?= htmlspecialchars($pb['payment_method']??'') ?></div><div>Rp <?= number_format($amt,0,',','.') ?> (<?= $pct ?>%)</div></div><div class="progress"><div class="progress-bar" role="progressbar" style="width: <?= $pct ?>%"></div></div><div class="small text-muted">Transaksi: <?= (int)($pb['tx']??0) ?></div></div><?php endforeach; if (empty($payBreak)): ?><div class="text-muted">Belum ada data</div><?php endif; ?></div></div>
  </div>
  <div class="col-lg-8">
    <div class="card"><div class="card-body">
      <div class="d-flex justify-content-between align-items-center mb-2"><h5 class="mb-0">Transaksi POS</h5><div><a class="btn btn-outline-primary btn-sm" href="../api/sales.php?format=csv&from=<?= urlencode($from) ?>&to=<?= urlencode($to) ?><?= $pay!==''?('&payment_method='.urlencode($pay)):'' ?>"><i class="bi bi-download"></i> Ekspor CSV</a></div></div>
      <div class="table-responsive" style="max-height: 460px; overflow-y: auto;"><table class="table table-hover"><thead><tr><th>Kode</th><th>Pelanggan</th><th>Metode</th><th>Total</th><th>Dibuat</th><th>Item</th></tr></thead><tbody id="sales-body">
      <?php foreach ($rows as $x): $code = (string)($x['code'] ?? ''); $cust = (string)($x['customer_name'] ?? ''); $pm = (string)($x['payment_method'] ?? ''); $tot = (float)($x['total'] ?? 0); $crt = (string)($x['created_at'] ?? ''); $sid = (int)($x['id'] ?? 0); $items = ($itemsMap[$sid] ?? []); $ilist = array_map(function($it){ $nm=(string)($it['item_name']??''); $q=(int)($it['qty']??0); $p=(float)($it['price']??0); $sub=$q*$p; return $nm.' x '.$q.' @ Rp '.number_format($p,0,',','.').' = Rp '.number_format($sub,0,',','.'); }, $items); ?>
      <tr><td><?= htmlspecialchars($code) ?></td><td><?= htmlspecialchars($cust) ?></td><td><a href="index.php?r=report/sales&payment_method=<?= urlencode($pm) ?>" class="text-decoration-none"><?= htmlspecialchars($pm) ?></a></td><td>Rp <?= number_format($tot,0,',','.') ?></td><td><?= htmlspecialchars($crt) ?></td><td class="small text-muted"><?= htmlspecialchars(implode('; ', $ilist)) ?></td></tr>
      <?php endforeach; if (empty($rows)): ?><tr><td colspan="6" class="text-muted">Belum ada data</td></tr><?php endif; ?>
      </tbody></table></div>
    </div></div>
  </div>
</div>
<div class="row g-3 mt-2">
  <div class="col-lg-12">
    <div class="card"><div class="card-body">
      <h5 class="mb-3">Tren Penjualan</h5>
      <div class="d-flex gap-2 mb-2">
        <a href="#" class="btn btn-sm btn-outline-secondary" id="trend-daily">Harian</a>
        <a href="#" class="btn btn-sm btn-outline-secondary" id="trend-weekly">Mingguan</a>
      </div>
      <div id="trend-chart" style="height:200px; position:relative; background:#f8f9fa; border:1px solid #e9ecef; border-radius:4px; overflow:hidden"></div>
    </div></div>
    <div class="card mt-3"><div class="card-body"><h5 class="mb-3">Top Item Terjual</h5><div class="table-responsive"><table class="table table-hover"><thead><tr><th>Item</th><th>Kuantitas</th><th>Nilai</th></tr></thead><tbody><?php foreach(($topItems??[]) as $ti): ?><tr><td><?= htmlspecialchars($ti['item_name']??'') ?></td><td><?= (int)($ti['qty']??0) ?></td><td>Rp <?= number_format((float)($ti['amount']??0),0,',','.') ?></td></tr><?php endforeach; if (empty($topItems)): ?><tr><td colspan="3" class="text-muted">Belum ada data</td></tr><?php endif; ?></tbody></table></div></div></div>
  </div>
</div>
<script>
const dailyData = <?= json_encode(array_map(function($r){ $label = $r['d'] ?? ($r['DATE(s.created_at)'] ?? ($r[0] ?? '')); $val = (float)($r['amount'] ?? ($r['SUM(s.total)'] ?? ($r[2] ?? 0))); return ['label'=>$label, 'value'=> $val ]; }, $dailyTrend??[])) ?>;
const weeklyData = <?= json_encode(array_map(function($r){ $label = $r['start_date'] ?? ($r['MIN(DATE(s.created_at))'] ?? ($r[1] ?? '')); $val = (float)($r['amount'] ?? ($r['SUM(s.total)'] ?? ($r[3] ?? 0))); return ['label'=>$label, 'value'=> $val ]; }, $weeklyTrend??[])) ?>;
function drawBars(data){const el=document.getElementById('trend-chart');el.innerHTML='';const w=el.clientWidth;const h=el.clientHeight;const max=Math.max(1,...data.map(x=>x.value));const barW=Math.max(8,Math.floor(w/Math.max(1,data.length)));data.forEach((x,i)=>{const bar=document.createElement('div');bar.style.position='absolute';bar.style.bottom='0';bar.style.left=(i*barW)+'px';bar.style.width=(barW-4)+'px';bar.style.height=Math.round((x.value/max)*h)+'px';bar.style.background='#0d6efd22';bar.style.border='1px solid #0d6efd55';bar.title=(x.label+' : Rp '+(Number(x.value).toLocaleString('id-ID')));el.appendChild(bar);});}
document.getElementById('trend-daily').addEventListener('click',function(e){e.preventDefault();drawBars(dailyData);});
document.getElementById('trend-weekly').addEventListener('click',function(e){e.preventDefault();drawBars(weeklyData);});
drawBars(dailyData);
// Fallback: jika baris kosong, ambil dari API
(function(){const tb=document.getElementById('sales-body');if(!tb)return;const rows=Array.from(tb.querySelectorAll('tr'));const hasDataRow=rows.some(function(tr){const tds=tr.querySelectorAll('td');return tds.length>=6 && String(tds[0].textContent||'').trim()!=='';});const isEmptyMsg=rows.length===1 && rows[0].querySelector('td') && String(rows[0].querySelector('td').textContent||'').includes('Belum ada data');if(hasDataRow||isEmptyMsg){return;}fetch('../api/sales.php').then(r=>r.json()).then(d=>{if(!d||!d.ok)return;const rws=Array.isArray(d.data)?d.data:[];tb.innerHTML='';rws.forEach(function(s){const tr=document.createElement('tr');const pm=String(s.payment_method||'');tr.setAttribute('data-code',String(s.code||''));tr.innerHTML=`<td>${String(s.code||'')}</td><td>${String(s.customer_name||'')}</td><td><a href="index.php?r=report/sales&payment_method=${encodeURIComponent(pm)}" class="text-decoration-none">${pm}</a></td><td>Rp ${(Number(s.total||0)).toLocaleString('id-ID')}</td><td>${String(s.created_at||'')}</td><td class="small text-muted"></td>`;tb.appendChild(tr);});const lim=50;const tasks=rws.slice(0,lim).map(function(s){const t=String(s.token||'');if(!t)return Promise.resolve({code:s.code,items:[]});return fetch('../api/sales.php?t='+encodeURIComponent(t)).then(r=>r.json()).then(dd=>({code:s.code,items:(dd&&dd.data&&Array.isArray(dd.data.items))?dd.data.items:[]})).catch(()=>({code:s.code,items:[]}));});Promise.all(tasks).then(function(details){details.forEach(function(d){const tr=tb.querySelector('tr[data-code="'+String(d.code||'')+'"]');if(!tr)return;const ilist=(d.items||[]).map(function(it){const nm=String(it.item_name||'');const q=Number(it.qty||0);const p=Number(it.price||0);const sub=q*p;return nm+' x '+q+' @ Rp '+p.toLocaleString('id-ID')+' = Rp '+sub.toLocaleString('id-ID');});const td=tr.querySelector('td:last-child');if(td){td.textContent=ilist.join('; ');} });});});})();
</script>
