<div class="dashboard-hero mb-4"><div class="d-flex justify-content-between align-items-center"><div><h2 class="mb-1">Garansi</h2><div class="subtitle">Kelola garansi servis dan klaim</div></div><div></div></div></div>
<div class="row g-4">
  <div class="col-lg-5"><div class="card"><div class="card-body"><h5 class="card-title">Buat Garansi</h5>
    <form id="wrn-form"><input type="hidden" id="wrn-id"><input type="hidden" id="wrn-token"><input type="hidden" id="wrn-ticket-token">
      <div class="mb-2"><label class="form-label">Tiket</label><input type="text" id="wrn-ticket" class="form-control" list="tkt-dl" placeholder="Ketik kode/nama lalu pilih"><datalist id="tkt-dl"></datalist></div>
      <div class="row g-2"><div class="col-md-6"><label class="form-label">Kode Garansi</label><input type="text" id="wrn-code" class="form-control" placeholder="otomatis jika kosong"></div><div class="col-md-6"><label class="form-label">Status</label><select id="wrn-status" class="form-select"><option>Active</option><option>Claimed</option><option>Expired</option></select></div></div>
      <div class="row g-2"><div class="col-md-4"><label class="form-label">Mulai</label><input type="date" id="wrn-start" class="form-control"></div><div class="col-md-4"><label class="form-label">Durasi (bulan)</label><input type="number" id="wrn-duration" class="form-control" value="3" min="1"></div><div class="col-md-4"><label class="form-label">Selesai</label><input type="date" id="wrn-end" class="form-control"></div></div>
      <div class="mb-2"><label class="form-label">Catatan</label><textarea id="wrn-notes" class="form-control" rows="2" placeholder="Syarat ketentuan garansi"></textarea></div>
      <div class="d-grid gap-2 mt-2"><button type="submit" class="btn btn-primary"><i class="bi bi-save me-2"></i>Simpan</button><button type="button" class="btn btn-outline-primary" id="wrn-reset"><i class="bi bi-plus-square me-2"></i>Bersihkan</button></div>
    </form>
  </div></div></div>
  <div class="col-lg-7"><div class="card"><div class="card-body">
    <div class="d-flex justify-content-between align-items-center mb-2"><h5 class="card-title mb-0">Daftar Garansi</h5><div class="input-group" style="max-width:280px;"><span class="input-group-text"><i class="bi bi-search"></i></span><input type="text" id="wrn-search" class="form-control" placeholder="Cari kode/tiket/nama"></div></div>
    <div class="table-responsive"><table class="table table-hover"><thead><tr><th>Kode</th><th>Tiket</th><th>Pelanggan</th><th class="text-nowrap">Selesai</th><th>Status</th><th>Update</th><th>Aksi</th></tr></thead><tbody id="wrn-list"></tbody></table></div>
  </div></div></div>
</div>
<script>
const WAPI='../api/warranties.php'; const TAPI='../api/tickets.php'; let TKT_MAP={};
function addMonths(dateStr, months){ const d=new Date(dateStr); d.setMonth(d.getMonth()+months); const m=('0'+(d.getMonth()+1)).slice(-2); const day=('0'+d.getDate()).slice(-2); return d.getFullYear()+'-'+m+'-'+day; }
function loadTickets(){ fetch(TAPI).then(r=>r.json()).then(d=>{ if(!d.ok)return; TKT_MAP={}; const dl=document.getElementById('tkt-dl'); if(dl) dl.innerHTML=''; (d.data||[]).forEach(x=>{ const label=(x.code||'')+' - '+(x.customer_name||''); TKT_MAP[label]=x; if(dl){ const opt=document.createElement('option'); opt.value=label; dl.appendChild(opt); } }); }); }
function fetchList(){ fetch(WAPI).then(r=>r.json()).then(d=>{ if(!d.ok)return; const q=document.getElementById('wrn-search').value.toLowerCase(); const rows=(d.data||[]).filter(x=> (x.code||'').toLowerCase().includes(q) || (x.ticket_code||'').toLowerCase().includes(q) || (x.customer_name||'').toLowerCase().includes(q)); const tbody=document.getElementById('wrn-list'); tbody.innerHTML=rows.map(x=>`<tr><td>${x.code||''}</td><td>${x.ticket_code||''}</td><td>${x.customer_name||''}</td><td>${x.end_date||''}</td><td><span class='badge bg-secondary'>${x.status||''}</span></td><td>${x.updated_at||''}</td><td><a class='btn btn-sm btn-outline-secondary me-1' href='index.php?r=warranty/slip&t=${encodeURIComponent(x.token)}' target='_blank' title='Cetak'><i class="bi bi-printer"></i></a><button class='btn btn-sm btn-outline-primary me-1' onclick='editW("${x.token}")'><i class="bi bi-pencil"></i></button><button class='btn btn-sm btn-outline-danger me-1' onclick='delW("${x.token}")'><i class="bi bi-trash"></i></button><button class='btn btn-sm btn-outline-success' onclick='claimW("${x.token}")'><i class="bi bi-shield-check"></i></button></td></tr>`).join(''); }); }
function editW(t){ fetch(WAPI+'?t='+encodeURIComponent(t)).then(r=>r.json()).then(d=>{ if(!d.ok||!d.data)return; const x=d.data; document.getElementById('wrn-id').value=x.id; document.getElementById('wrn-token').value=t; document.getElementById('wrn-code').value=x.code||''; document.getElementById('wrn-status').value=x.status||'Active'; document.getElementById('wrn-start').value=x.start_date||''; document.getElementById('wrn-end').value=x.end_date||''; document.getElementById('wrn-duration').value=(x.duration_months||3); document.getElementById('wrn-notes').value=x.notes||''; }); }
function delW(t){ if(!confirm('Hapus garansi ini?'))return; fetch(WAPI+'?t='+encodeURIComponent(t),{ method:'DELETE' }).then(r=>r.json()).then(d=>{ if(d.ok) fetchList(); }); }
function claimW(t){ fetch(WAPI,{ method:'PUT', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ t, status:'Claimed' }) }).then(r=>r.json()).then(d=>{ if(d.ok) fetchList(); }); }
document.getElementById('wrn-form').addEventListener('submit', function(e){ e.preventDefault(); const id=document.getElementById('wrn-id').value; const label=document.getElementById('wrn-ticket').value; const t=TKT_MAP[label]; const payload={ id: id? parseInt(id,10): undefined, code: document.getElementById('wrn-code').value.trim(), start_date: document.getElementById('wrn-start').value, end_date: document.getElementById('wrn-end').value, duration_months: parseInt(document.getElementById('wrn-duration').value,10)||null, status: document.getElementById('wrn-status').value, notes: document.getElementById('wrn-notes').value }; if(t) payload.ticket_token=t.token; const method=id? 'PUT':'POST'; fetch(WAPI,{ method, headers:{'Content-Type':'application/json'}, body: JSON.stringify(payload) }).then(r=>r.json()).then(d=>{ if(d.ok){ document.getElementById('wrn-form').reset(); document.getElementById('wrn-id').value=''; fetchList(); } }); });
document.getElementById('wrn-reset').addEventListener('click', function(){ document.getElementById('wrn-form').reset(); document.getElementById('wrn-id').value=''; });
document.getElementById('wrn-search').addEventListener('input', fetchList);
function updateEnd(){ const s=document.getElementById('wrn-start').value; const dm=parseInt(document.getElementById('wrn-duration').value,10)||3; if(s){ document.getElementById('wrn-end').value=addMonths(s,dm); } }
document.getElementById('wrn-start').addEventListener('change', updateEnd);
document.getElementById('wrn-duration').addEventListener('input', updateEnd);
loadTickets(); fetchList();
</script>
