<div class="dashboard-hero mb-4"><div class="d-flex justify-content-between align-items-center"><div><h2 class="mb-1">Supplier</h2><div class="subtitle">Kelola pemasok</div></div><div></div></div></div>
<div class="row g-4"><div class="col-lg-5"><div class="card"><div class="card-body"><h5 class="card-title">Form Supplier</h5>
<form id="sup-form"><input type="hidden" id="sup-id"><div class="mb-2"><label class="form-label">Nama</label><input type="text" id="sup-name" class="form-control" required></div><div class="mb-2"><label class="form-label">No HP</label><input type="text" id="sup-phone" class="form-control"></div><div class="mb-2"><label class="form-label">Email</label><input type="email" id="sup-email" class="form-control"></div><div class="mb-2"><label class="form-label">Alamat</label><input type="text" id="sup-address" class="form-control"></div><div class="mb-2"><label class="form-label">Catatan</label><textarea id="sup-note" class="form-control" rows="2"></textarea></div><div class="d-grid gap-2 mt-2"><button type="submit" class="btn btn-primary"><i class="bi bi-save me-2"></i>Simpan</button><button type="button" class="btn btn-outline-primary" id="sup-reset"><i class="bi bi-plus-square me-2"></i>Bersihkan</button></div></form>
</div></div></div>
<div class="col-lg-7"><div class="card"><div class="card-body">
<div class="d-flex justify-content-between align-items-center mb-2"><h5 class="card-title mb-0">Daftar Supplier</h5><div class="input-group" style="max-width:280px;"><span class="input-group-text"><i class="bi bi-search"></i></span><input type="text" id="sup-search" class="form-control" placeholder="Cari nama/HP"></div></div>
<div class="table-responsive"><table class="table table-hover"><thead><tr><th>Nama</th><th>HP</th><th>Email</th><th>Alamat</th><th>Aksi</th></tr></thead><tbody id="sup-list"></tbody></table></div>
</div></div></div></div>
<script>const SAPI='../api/suppliers.php';function loadSup(){fetch(SAPI).then(r=>r.json()).then(d=>{if(!d.ok)return;const q=document.getElementById('sup-search').value.toLowerCase();const rows=(d.data||[]).filter(x=>(x.name||'').toLowerCase().includes(q)||(x.phone||'').toLowerCase().includes(q));const tbody=document.getElementById('sup-list');tbody.innerHTML=rows.map(x=>`<tr><td>${x.name||''}</td><td>${x.phone||''}</td><td>${x.email||''}</td><td>${x.address||''}</td><td><div class='btn-group btn-group-sm'><button class='btn btn-outline-primary' onclick='editSup("${x.token}")'><i class='bi bi-pencil'></i></button><button class='btn btn-outline-danger' onclick='delSup("${x.token}")'><i class='bi bi-trash'></i></button></div></td></tr>`).join('');});}
function editSup(t){fetch(SAPI+'?t='+encodeURIComponent(t)).then(r=>r.json()).then(d=>{if(!d.ok||!d.data)return;const x=d.data;document.getElementById('sup-id').value=x.id;document.getElementById('sup-name').value=x.name||'';document.getElementById('sup-phone').value=x.phone||'';document.getElementById('sup-email').value=x.email||'';document.getElementById('sup-address').value=x.address||'';document.getElementById('sup-note').value=x.note||'';});}
function delSup(t){if(!confirm('Hapus supplier ini?'))return;fetch(SAPI+'?t='+encodeURIComponent(t),{method:'DELETE'}).then(r=>r.json()).then(d=>{if(d.ok)loadSup();});}
document.getElementById('sup-form').addEventListener('submit',function(e){e.preventDefault();const id=document.getElementById('sup-id').value;const payload={id:id?parseInt(id,10):undefined,name:document.getElementById('sup-name').value.trim(),phone:document.getElementById('sup-phone').value.trim(),email:document.getElementById('sup-email').value.trim(),address:document.getElementById('sup-address').value.trim(),note:document.getElementById('sup-note').value.trim()};const method=id?'PUT':'POST';fetch(SAPI,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(r=>r.json()).then(d=>{if(d.ok){document.getElementById('sup-form').reset();document.getElementById('sup-id').value='';loadSup();}});});
document.getElementById('sup-reset').addEventListener('click',function(){document.getElementById('sup-form').reset();document.getElementById('sup-id').value='';});document.getElementById('sup-search').addEventListener('input',loadSup);loadSup();</script>

