<div class="dashboard-hero mb-4"><div class="d-flex justify-content-between align-items-center"><div><h2 class="mb-1">Kelola Users</h2><div class="subtitle">Tambah, ubah, hapus pengguna</div></div><div></div></div></div>
<div class="row g-4"><div class="col-lg-5"><div class="card"><div class="card-body"><h5 class="card-title">Form User</h5>
<form id="user-form"><input type="hidden" id="user-id"><div class="mb-2"><label class="form-label">Nama</label><input type="text" id="user-name" class="form-control" required></div><div class="mb-2"><label class="form-label">Email</label><input type="email" id="user-email" class="form-control" required></div><div class="mb-2"><label class="form-label">Password</label><input type="password" id="user-password" class="form-control" placeholder="Kosongkan saat edit jika tidak diubah"></div><div class="mb-2"><label class="form-label">Role</label><select id="user-role" class="form-select"><option value="admin">Admin</option><option value="kasir">Kasir</option><option value="teknisi">Teknisi</option></select></div><div class="d-grid gap-2 mt-2"><button type="submit" class="btn btn-primary"><i class="bi bi-save me-2"></i>Simpan</button><button type="button" class="btn btn-outline-primary" id="user-reset"><i class="bi bi-plus-square me-2"></i>Bersihkan</button></div></form>
</div></div></div>
<div class="col-lg-7"><div class="card"><div class="card-body">
<div class="d-flex justify-content-between align-items-center mb-2"><h5 class="card-title mb-0">Daftar Users</h5><div class="input-group" style="max-width:280px;"><span class="input-group-text"><i class="bi bi-search"></i></span><input type="text" id="user-search" class="form-control" placeholder="Cari nama/email"></div></div>
<div class="table-responsive"><table class="table table-hover"><thead><tr><th>Nama</th><th>Email</th><th>Role</th><th>Aksi</th></tr></thead><tbody id="user-list"></tbody></table></div>
</div></div></div></div>
<script>
const ROOT_PATH = location.pathname.replace(/\/public\/.*/, '/');
const UAPI_ACTIVE = location.origin + ROOT_PATH + 'api/users.php';
function asJson(res){ if(!res.ok) throw new Error('HTTP '+res.status); return res.json(); }
function loadUsers(){fetch(UAPI_ACTIVE,{credentials:'same-origin'}).then(asJson).then(d=>{if(!d)return;const q=document.getElementById('user-search').value.toLowerCase();const rows=(d.data||[]).filter(x=>(x.name||'').toLowerCase().includes(q)||(x.email||'').toLowerCase().includes(q));const tbody=document.getElementById('user-list');tbody.innerHTML=rows.map(x=>`<tr><td>${x.name||''}</td><td>${x.email||''}</td><td><span class='badge bg-secondary'>${x.role||''}</span></td><td><div class='btn-group btn-group-sm'><button class='btn btn-outline-primary' onclick='editU("${x.token}")'><i class='bi bi-pencil'></i></button><button class='btn btn-outline-danger' onclick='delU("${x.token}")'><i class='bi bi-trash'></i></button></div></td></tr>`).join('');}).catch(()=>{const tbody=document.getElementById('user-list');tbody.innerHTML='';});}
function editU(t){fetch(UAPI_ACTIVE+'?t='+encodeURIComponent(t),{credentials:'same-origin'}).then(asJson).then(d=>{if(!d||!d.data)return;const x=d.data;document.getElementById('user-id').value=x.id;document.getElementById('user-name').value=x.name||'';document.getElementById('user-email').value=x.email||'';document.getElementById('user-role').value=x.role||'kasir';document.getElementById('user-password').value='';}).catch(()=>{});}
function delU(t){if(!confirm('Hapus pengguna ini?'))return;fetch(UAPI_ACTIVE+'?t='+encodeURIComponent(t),{method:'DELETE',credentials:'same-origin'}).then(asJson).then(d=>{if(d.ok)loadUsers();}).catch(()=>{});}
document.getElementById('user-form').addEventListener('submit',function(e){e.preventDefault();const id=document.getElementById('user-id').value;const payload={id:id?parseInt(id,10):undefined,name:document.getElementById('user-name').value.trim(),email:document.getElementById('user-email').value.trim(),password:document.getElementById('user-password').value,role:document.getElementById('user-role').value};const method=id?'PUT':'POST';fetch(UAPI_ACTIVE,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),credentials:'same-origin'}).then(asJson).then(d=>{if(d&&d.ok){document.getElementById('user-form').reset();document.getElementById('user-id').value='';loadUsers();}}).catch(()=>{});});
document.getElementById('user-reset').addEventListener('click',function(){document.getElementById('user-form').reset();document.getElementById('user-id').value='';});document.getElementById('user-search').addEventListener('input',loadUsers);loadUsers();
</script>
