<div class="dashboard-hero mb-4"><div class="d-flex justify-content-between align-items-center"><div><h2 class="mb-1">Pembelian</h2><div class="subtitle">Pesanan pembelian dan penerimaan stok</div></div><div></div></div></div>
<div class="row g-4"><div class="col-lg-5"><div class="card"><div class="card-body"><h5 class="card-title">Buat PO</h5>
<form id="po-form"><input type="hidden" id="po-id"><div class="mb-2"><label class="form-label">Supplier</label><input type="text" id="po-supplier" class="form-control" list="sup-dl" placeholder="Ketik nama lalu pilih"><datalist id="sup-dl"></datalist></div><div class="mb-2"><label class="form-label">Catatan</label><textarea id="po-note" class="form-control" rows="2"></textarea></div>
<div class="mb-2"><label class="form-label">Item</label><div class="row g-2"><div class="col-6"><input type="text" id="pi-name" class="form-control" list="item-dl" placeholder="Nama item"><datalist id="item-dl"></datalist></div><div class="col-3"><input type="number" id="pi-qty" class="form-control" placeholder="Qty" value="1"></div><div class="col-3"><input type="number" step="0.01" id="pi-price" class="form-control" placeholder="Harga"></div></div><div class="d-grid mt-2"><button class="btn btn-outline-secondary" type="button" id="pi-add"><i class="bi bi-plus"></i> Tambah Item</button></div></div>
<div class="table-responsive mt-2"><table class="table table-sm"><thead><tr><th>Item</th><th class="text-end">Qty</th><th class="text-end">Harga</th><th class="text-end">Subtotal</th><th></th></tr></thead><tbody id="pi-list"></tbody><tfoot><tr><td colspan="3" class="text-end">Total</td><td class="text-end" id="po-total">Rp0</td><td></td></tr></tfoot></table></div>
<div class="d-grid gap-2 mt-2"><button type="submit" class="btn btn-primary"><i class="bi bi-save me-2"></i>Simpan PO</button><button type="button" class="btn btn-outline-primary" id="po-reset"><i class="bi bi-plus-square me-2"></i>Bersihkan</button></div></form>
</div></div></div>
<div class="col-lg-7"><div class="card"><div class="card-body">
<div class="d-flex justify-content-between align-items-center mb-2"><h5 class="card-title mb-0">Daftar PO</h5><div class="input-group" style="max-width:280px;"><span class="input-group-text"><i class="bi bi-search"></i></span><input type="text" id="po-search" class="form-control" placeholder="Cari kode/supplier"></div></div>
<div class="table-responsive"><table class="table table-hover"><thead><tr><th>Kode</th><th>Supplier</th><th>Status</th><th>Dibuat</th><th>Aksi</th></tr></thead><tbody id="po-list"></tbody></table></div>
</div></div></div></div>
<script>
const PAPI='../api/purchases.php';const SAPI='../api/suppliers.php';const IAPI='../api/items.php';let SUPMAP={};let ITEMMAP={};let PITEMS=[];function fmtIDR(n){return 'Rp '+(Number(n||0)).toLocaleString('id-ID');}
function loadSup(){fetch(SAPI).then(r=>r.json()).then(d=>{if(!d.ok)return;SUPMAP={};const dl=document.getElementById('sup-dl');dl.innerHTML='';(d.data||[]).forEach(x=>{const label=(x.name||'')+' ('+(x.phone||'')+')';SUPMAP[label]=x;const o=document.createElement('option');o.value=label;dl.appendChild(o);});});}
function loadItems(){fetch(IAPI).then(r=>r.json()).then(d=>{if(!d.ok)return;ITEMMAP={};const dl=document.getElementById('item-dl');dl.innerHTML='';(d.data||[]).forEach(x=>{ITEMMAP[x.name||'']=x;const o=document.createElement('option');o.value=x.name||'';dl.appendChild(o);});});}
function renderPItems(){const tbody=document.getElementById('pi-list');let total=0;tbody.innerHTML=PITEMS.map((it,i)=>{const sub=(Number(it.qty)||0)*(Number(it.price)||0);total+=sub;return `<tr><td>${it.name||''}</td><td class='text-end'>${it.qty||0}</td><td class='text-end'>${fmtIDR(it.price||0)}</td><td class='text-end'>${fmtIDR(sub)}</td><td class='text-end'><button type='button' class='btn btn-sm btn-outline-danger' onclick='delPi(${i})'><i class=\"bi bi-x\"></i></button></td></tr>`}).join('');document.getElementById('po-total').innerText=fmtIDR(total);}function delPi(i){PITEMS.splice(i,1);renderPItems();}
document.getElementById('pi-add').addEventListener('click',function(){const name=document.getElementById('pi-name').value.trim();const qty=Number(document.getElementById('pi-qty').value||0);const price=Number(document.getElementById('pi-price').value||0);if(!name||qty<=0||price<0)return;const item=ITEMMAP[name];const item_id=item?item.id:undefined;PITEMS.push({item_id,name,qty,price});document.getElementById('pi-name').value='';document.getElementById('pi-qty').value='1';document.getElementById('pi-price').value='';renderPItems();});
function loadPO(){fetch(PAPI).then(r=>r.json()).then(d=>{if(!d.ok)return;const q=document.getElementById('po-search').value.toLowerCase();const rows=(d.data||[]).filter(x=>(x.code||'').toLowerCase().includes(q)||(x.supplier_name||'').toLowerCase().includes(q));const tbody=document.getElementById('po-list');tbody.innerHTML=rows.map(x=>`<tr><td>${x.code||''}</td><td>${x.supplier_name||''}</td><td><span class='badge ${x.status==='Received'?'bg-success':(x.status==='Returned'?'bg-warning':'bg-secondary')}'>${x.status||''}</span></td><td>${x.created_at||''}</td><td><div class='btn-group btn-group-sm'>${x.status==='Draft'?`<button class='btn btn-outline-primary' onclick='openPO("${x.token}")'><i class='bi bi-eye'></i></button><button class='btn btn-outline-success' onclick='recvPO("${x.token}")'><i class='bi bi-box-arrow-in-down'></i> Terima</button><button class='btn btn-outline-danger' onclick='delPO("${x.token}")'><i class='bi bi-trash'></i></button>`:(x.status==='Received'?`<button class='btn btn-outline-primary' onclick='openPO("${x.token}")'><i class='bi bi-eye'></i></button><button class='btn btn-outline-warning' onclick='retPO("${x.token}")'><i class='bi bi-box-arrow-up'></i> Retur</button>`:`<button class='btn btn-outline-primary' onclick='openPO("${x.token}")'><i class='bi bi-eye'></i></button>`)}</div></td></tr>`).join('');});}
function openPO(t){fetch(PAPI+'?t='+encodeURIComponent(t)).then(r=>r.json()).then(d=>{if(!d.ok||!d.data)return;const x=d.data;alert(`PO ${x.code}\nSupplier: ${x.supplier_name||''}\nItem: ${(x.items||[]).map(it=>it.item_name+" x "+it.qty).join(', ')}`);});}
function recvPO(t){if(!confirm('Terima barang untuk PO ini?'))return;fetch(PAPI,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({t,action:'receive'})}).then(r=>r.json()).then(d=>{if(d.ok)loadPO();});}
function retPO(t){if(!confirm('Retur barang untuk PO ini?'))return;fetch(PAPI,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({t,action:'return'})}).then(r=>r.json()).then(d=>{if(d.ok)loadPO();});}
function delPO(t){if(!confirm('Hapus PO Draft ini?'))return;fetch(PAPI+'?t='+encodeURIComponent(t),{method:'DELETE'}).then(r=>r.json()).then(d=>{if(d.ok)loadPO();});}
document.getElementById('po-form').addEventListener('submit',function(e){e.preventDefault();const sname=document.getElementById('po-supplier').value.trim();const sup=SUPMAP[sname];const payload={supplier_id:sup?sup.id:undefined,note:document.getElementById('po-note').value.trim(),items:PITEMS.map(it=>({item_id:it.item_id,name:it.name,qty:it.qty,price:it.price}))};fetch(PAPI,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(r=>r.json()).then(d=>{if(d.ok){document.getElementById('po-form').reset();PITEMS=[];renderPItems();loadPO();}});});
document.getElementById('po-reset').addEventListener('click',function(){document.getElementById('po-form').reset();PITEMS=[];renderPItems();});document.getElementById('po-search').addEventListener('input',loadPO);loadSup();loadItems();renderPItems();loadPO();
</script>
